title: '朱高攀的技术博客'
subtitle: ''
public_url: 'https://winwink.github.io'
keywords: ''
owner:
  name: '朱高攀'
  mail: 'winwink(at)qq.com'
  weibo: 'https://weibo.com/winwink'
disqus:
  short_name: 'winwink-github'
paginate: 12
exclude: ['start-jekyll.sh', 'start-jekyll.bat', 'bower.json']
encoding: utf-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
host: 127.0.0.1
port: 4004
